### ISSUE TITLE
Q: Status RS3?

### ISSUE THREAD

**Issue by marceloverdijk** [aichaos/rivescript3#1]
Hi @kirsle , it's been some time but later this year I might get involved in another chatbot implementation. I was looking a bit around and found this information regarding RS3. Did you made any progress on it and what is the status?

**Comment by kirsle** [comment]
Hey Marcel,

Not much progress was made on this, at all. 😄 It was an idea I had during the "second wave of chatbots" (~2016 when Facebook, Microsoft and others had bot platforms and there was a boom of interest in bots for a time... after the "first wave" of bots ~2000 with SmarterChild on AIM and the A.L.I.C.E. bots).

If I were going to tackle it now, I'd look at using the Rust language instead of Go... for its support for building C-compatible shared objects for easy bindings to other programming languages, but without the fat Go runtime environment with its garbage collection and so on. Having the 5 different implementations of RiveScript 2 became a liability after a while as they all became slow to change as I didn't want one version getting too far ahead of the others on feature support.

The other repo, https://github.com/aichaos/rivescript.next has some more notes I wrote down about the problems and limitations that RiveScript 2 has that would be taken into account for RS3 to do better.

I have other personal projects now that compete for my free time, tho if chatbots see a third wave of interest it may be a good time to dust off these ideas and see what can be done!

**Comment by marceloverdijk** [comment]
I fully understand!

I also lost a bit of interest during wave 2 bc it didn't lift off at our clients and other (side) projects popped up as well.

Thanks for explaining the status and let's see how it goes!
